FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY Consumer.java ./
RUN curl -L -o rabbitmq-client.jar https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/5.20.0/amqp-client-5.20.0.jar && \
    curl -L -o slf4j-api.jar https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar && \
    curl -L -o slf4j-simple.jar https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.36/slf4j-simple-1.7.36.jar && \
    javac -cp "rabbitmq-client.jar:slf4j-api.jar" Consumer.java
CMD ["java", "-cp", ".:rabbitmq-client.jar:slf4j-api.jar:slf4j-simple.jar", "Consumer"]
