apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fix-rabbitmq-permissions
  namespace: default
spec:
  selector:
    matchLabels:
      app: fix-permissions
  template:
    metadata:
      labels:
        app: fix-permissions
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: fix-permissions
        image: busybox
        command:
        - sh
        - -c
        - |
          mkdir -p /data/rabbitmq/data-0 /data/rabbitmq/data-1 /data/rabbitmq/data-2
          chown -R 999:999 /data/rabbitmq
          chmod -R 755 /data/rabbitmq
          echo "Permissions fixed. Sleeping..."
          sleep infinity
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-data
          mountPath: /data
      volumes:
      - name: host-data
        hostPath:
          path: /data
