apiVersion: batch/v1
kind: Job
metadata:
  name: rabbit-producer
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      restartPolicy: Never
      containers:
        - name: producer
          image: ghcr.io/gmbenz/producer:latest
          env:
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
