apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: management
      port: 15672
      targetPort: 15672
